require "active_record/connection_adapters/sqlanywhere_jdbc_in4systems_adapter"
require "activerecord-import/adapters/sqlanywhere_jdbc_in4systems_adapter"

class ActiveRecord::ConnectionAdapters::SQLAnywhereJdbcIn4systemsAdapter
  include ActiveRecord::Import::SQLAnywhereJdbcIn4systemsAdapter
end

